server:
  port: ${server.port}
  undertow:
    io-threads: 8
    worker-threads: 512
    buffer-size: 4096
    direct-buffers: true
    max-http-post-size: 52428800

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  application:
    name: demo
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  messages:
      basename: i18n/messages
      cache-seconds: 3600
      encoding: UTF-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: ${ds.database}
      driver-class: com.mysql.jdbc.Driver
      username: ${ds.username}
      password: ${ds.password}
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-While-Idle: true
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
  #    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      log-slow-sql: true
